### ISSUE TITLE
Confuse about cross attention

### ISSUE THREAD

**Issue by XinZhang0526** [alibaba-yuanjing-aigclab/ViViD#12]
Hi, @BecauseImBatman0
I noticed that [cross attention layers](https://github.com/alibaba-yuanjing-aigclab/ViViD/blob/main/src/models/mutual_self_attention.py#L240C16-L253C33) were not used by vivid. 
Why?
![image](https://github.com/user-attachments/assets/0e625430-cd79-4892-8b4b-315fbc26c881)

**Comment by BecauseImBatman0** [comment]
Hi, in fact, the cross-attention layers work correctly in ViViD. I don't know if your issue is about the indentation at line 240 or the syntax. If it's the former, this code block is within an **if** statement (line 219). If it's the latter, see:
![image](https://github.com/user-attachments/assets/fef99a93-209c-41f5-801f-efeb5de604f7)

**Comment by XinZhang0526** [comment]
Thanks a lot for your reply. I means that: the variable, hidden_states_uc (line 240) which should be the FF input, is not used in the following code. So, I'm confused. It seems that we calculate the cross attention, but we do not used it in the forward process.
I think that it should be:
hidden_states = self.ff(self.norm3(hidden_states_uc )) + hidden_states (line 253)
rather than:
hidden_states = self.ff(self.norm3(hidden_states )) + hidden_states (line 253)

**Comment by XinZhang0526** [comment]
Thanks a lot for your reply. 
I means that the variable,  hidden_states_uc (line 240) which should be the input of FF, is not used in the following code.
So, I'm confused. It seems that we caculate the cross attention output, but do not use it.
More intuitively, I think it should be:
hidden_states = self.ff(self.norm3(hidden_states_uc)) + hidden_states (line 253)
rather than:
hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states (line 253)

Is it my understanding of the code that's wrong?

**Comment by BecauseImBatman0** [comment]
holy.........
you are right, I made a mistake here. It should be hidden_states rather than hidden_states_uc at line 240. Thanks for pointing this out. I am sorry for my oversight.🥲

**Comment by XinZhang0526** [comment]
But I find this result will not change a lot. It's interesting. hhhhhh
Anyway, thanks a lot
