### ISSUE TITLE
能运行吗

### ISSUE THREAD

**Issue by xiyuxiaoxiao** [alibaba-yuanjing-aigclab/ViViD#14]
安装完依赖后,运行脚本报错,加载本地denoising_unet_path报错。 torch.load(config.denoising_unet_path, map_location="cpu")

**Comment by xiyuxiaoxiao** [comment]
我的环境: PyTorch  2.1.0
Python  3.10(ubuntu22.04)
Cuda  12.1

**Comment by BecauseImBatman0** [comment]
改一下config里面的模型路径试试呢？

**Comment by xiyuxiaoxiao** [comment]
路径对的,有没有详细的保姆级的教程,尤其环境依赖这块
