### ISSUE TITLE
sam_agnostic.py 的输入数据是什么？

### ISSUE THREAD

**Issue by ohmydroid** [alibaba-yuanjing-aigclab/ViViD#22]
https://github.com/alibaba-yuanjing-aigclab/ViViD/blob/d8a01e8cd1bb60fb1993e3e2f9a9f263af62ab16/tools/sam_agnostic.py#L70

**Comment by Zhiying-Li-dot** [comment]
您好，我也是遇到这个问题，请问您解决了吗？

**Comment by ohmydroid** [comment]
@Zhiying-Li-dot 没有，最近没有跟这个项目
